### ISSUE TITLE
bug: imports in the `pdm_build.py` file should be declared as build-system requires

### ISSUE THREAD

**Issue by kemingy** [pdm-project/pdm-shear#1]
Let's say I have a `pdm_build.py` file that `import httpx`, it should be declared as:

```toml
[build-system]
requires = ["pdm-backend", "httpx"]
build-backend = "pdm.backend"
```

For now it raises error:

```txt
Missing dependency: httpx used by the following files:
/home/GitHub/offapi/pdm_build.py:4
```
